### ISSUE TITLE
Start to the local directory

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#103]
- bug report? no
- feature request? yes
- version: 3.0-dev

### Description
When the instance of Deployer is created, it will be nice to move to the current directory. 

So all jobs (Before[], After[], etc..) can be used from that directory.

A simple possiblility in the Deployer __construct method:

```
public function __construct(Server $server, string $localDir, Logger $logger)
{
	$this->localDir = realpath($localDir);
	chdir($this->localDir);
        ...        
}
```

**Comment by dg** [comment]
It was removed due to #38 and IMHO cannot be reverted because it would be a huge BC break.

**Comment by laurentmuller** [comment]
OK for me. I will use a batch file.
