### ISSUE TITLE
Always Job

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#104]
- bug report? no
- feature request? yes
- version: 3.0-dev

### Description
This will be nice to have an entry for jobs that must always be running; even though no changes have been made.

For example in my scenario, I update my project with a before job and an after job:

```
before[] = local: "composer install --no-dev
after[] = local: "composer install
```
If no change occurs, the after job is never called and my projet is not up to date. A new kind of job entry can be created like follow:

`always[] = local: "composer install`

This job would be called regardless of the result of the update.

**Comment by dg** [comment]
See this https://github.com/dg/ftp-deployment/issues/88#issuecomment-264062692

**Comment by laurentmuller** [comment]
OK for me.
