### ISSUE TITLE
 JavaScript file is not compressed

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#105]
- bug report? yes
- feature request? yo
- version: 3.0-dev

### Description
An error occurs when compressing the java script file.

### Steps To Reproduce

- Creates a new configuration file (for example `config.ini`).
- Set option `preprocess = 1` 
- Add a directory whit some JS files
- run `php deployment.phar config.ini`

The `deployment.log` show the following error:
```
Compressing D:\symfony\web\js\post_edit.js
Error while executing "java" -jar "phar://D:/Prod/plugins/deployment.phar/src/vendor/Google-Closure-Compiler/compiler.jar" --warning_level QUIET
Error: Unable to access jarfile phar://D:/Prod/plugins/deployment.phar/src/vendor/Google-Closure-Compiler/compiler.jar
```
And the java script file is not compressed.

**Remark:**
What is strange that the `deployment.phar` file (version 3.0) is only 13 Kb size and the `compiler.jar` file from Google Closure Compiler is already 7551 Kb!

I do something wrong?

**Comment by dg** [comment]
You are right that compression does not work when phar version is used because compiler.jar is missing. I'll try to figure out how to fix it.
