### ISSUE TITLE
Unable to purge with FileServer

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#109]
Version: 3.0.1

### Bug Description
When purge within the `FileServer`, the path used is not within the root directory. The code use only the `$dir` parameter.

### Steps To Reproduce
Just try to deploy when the directory to purge does not exist.

### Expected Behavior
The purge function must use the full path..

### Possible Solution
- The function must build the full path: `$path = $this->root . $dir;`.
- The function must check that the full path exist.
- The `RecursiveDirectoryIterator` must use the full path. 
- The `RecursiveDirectoryIterator` must use the `SKIP_DOTS`  flags. If not, the `'.'` and `'..'` directories are also returned and an exception occurs when try to delete.

This is my updated code:
```
public function purge(string $dir, callable $progress = null): void
{
    $path = $this->root . $dir;
    if (!file_exists($path)) {
        return;
    }

    $directory = new \RecursiveDirectoryIterator($path, \FilesystemIterator::SKIP_DOTS);
    $iterator = new \RecursiveIteratorIterator($directory, \RecursiveIteratorIterator::CHILD_FIRST);

    foreach ($iterator as  $name => $file) {
        $file->isDir() ? rmdir($name) : unlink($name);
        if ($progress) {
            $progress($name);
        }
    }
}
```

**Comment by dg** [comment]
Feel free to send PR :-)

**Comment by dg** [comment]
I think that SKIP_DOTS is the default in RecursiveDirectoryIterator.

**Comment by laurentmuller** [comment]
The default value is `FilesystemIterator::KEY_AS_PATHNAME | FilesystemIterator::CURRENT_AS_FILEINFO`.

Please check the documentation at: [RecursiveDirectoryIterator.construct](http://php.net/manual/fr/recursivedirectoryiterator.construct.php)

**Comment by dg** [comment]
Oh, it differs from http://php.net/manual/en/filesystemiterator.construct.php.
