### ISSUE TITLE
Make array of deleted/uploaded files available for running jobs

### ISSUE THREAD

**Issue by ne0-cz** [dg/ftp-deployment#112]
It might be useful to have arrays of deleted and uploaded files available for a job.

Since every callable job has the instance of the `Deployer` passed as an argument, the implementation might be as easy as `%s/$toUpload/$this->toUpload/g` (and making this member variable public).

In my case this would be really useful for a CDN. My static assets use  part of their MD5 hash as filename - so whenever e.g. the CSS is changed, the old file gets deleted and a new file is uploaded. The CDN supports API, so I could easily prefetch the new file and purge the old file (which now has to be done manually).

It'd also be interesting to have some queue of cleanup jobs - things to run after successful deployment - this CDN prefetch/purge would be ideal candidate for this one, since the site no longer needs to be in the maintenance mode (CACHE-MISS is not that big deal during those few seconds).

But I understand this might be beyond the scope of this project.
I'm aware that the cleanup job closely resembles the always job which was already discussed in https://github.com/dg/ftp-deployment/issues/104 and https://github.com/dg/ftp-deployment/issues/88 - but the batch file wouldn't work in this case since the task depends on the files which were actually uploaded / deleted. Thanks.

**Comment by dg** [comment]
ad *$toUpload => $this->toUpload* - it is ok, feel free to send PR

ad *things to run after successful deployment* - there are `afterUpload` and `after` jobs, is not that what you need?
