### ISSUE TITLE
Add Log entry when expanding files within the Preprocessor

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#114]
When a CSS file contains an `@import` directive or a JS file contains a `#include` directive,it will be nice to output informations when expanding within the Preprocessor.

For example for JS:
```php
public function expandApacheImports(string $content, string $origFile): string
    ...
    if (is_file($file)) {
        $this->logger->log("Expanding $file");
        ...
    }
    $this->logger->log("Expanding file $file not found!", 'red');
    ...
```
So, we can check if an error occurs while deploying files.

**Comment by dg** [comment]
Ok. Can you send pull request?

**Comment by laurentmuller** [comment]
Added a pull request.
