### ISSUE TITLE
First deployment .deployment file empty error 

### ISSUE THREAD

**Issue by xpackal5** [dg/ftp-deployment#116]
Version: 3.1.0

### Bug Description
If I do first deploy, it throw file not found (.deployment) error.
If I create empty .deployment file on remote. it throws.
`Live mode        
Connecting to server        
ErrorException: gzinflate(): data error in /var/www/html/vendor/dg/ftp-deployment/src/Deployment/Deployer.php:203
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(2, 'gzinflate(): da...', '/var/www/html/v...', 203, Array)
#1 /var/www/html/vendor/dg/ftp-deployment/src/Deployment/Deployer.php(203): gzinflate('')
#2 /var/www/html/vendor/dg/ftp-deployment/src/Deployment/Deployer.php(101): Deployment\Deployer->loadDeploymentFile()
#3 /var/www/html/vendor/contributte/deployer-extension/src/Runner.php(77): Deployment\Deployer->deploy()
#4 /var/www/html/vendor/contributte/deployer-extension/src/Manager.php(28): Contributte\Deployer\Runner->run(Object(Contributte\Deployer\Config\Config))
#5 /var/www/html/bin/deploy.php(26): Contributte\Deployer\Manager->deploy()
#6 /var/www/html/bin/deploy_preprod(5): require('/var/www/html/b...')
#7 {main}`

What must be a content of new .deployment file?

**Comment by hopocode** [comment]
Please include your config file without credential.s Thanks
