### ISSUE TITLE
Local deployment does not work

### ISSUE THREAD

**Issue by petrnemec** [dg/ftp-deployment#118]
Version: 3.1

### Bug Description
Local deployment (with file URI scheme) does not work.  
It ends up either with "_Error: Missing or invalid 'remote' URL in config._" when no host used or with "_Error: File exists_" when creating directory (mkdir) when "localhost" used.

### Steps To Reproduce
remote = file:///directory  
remote = file://localhost/directory

**Comment by dg** [comment]
Try `remote = file://directory`

// #101

**Comment by dg** [comment]
@petrnemec  Did it help?
