### ISSUE TITLE
uploading many files with SSL: crash on rename

### ISSUE THREAD

**Issue by pad52** [dg/ftp-deployment#121]
Version: 3.1

### Bug Description

When try to upload many files, when starts to rename it crashes:

( 1188 of 15285) Renaming /wp-content/plugins/divi-builder/includes/builder/frontend-builder/assets/vendors/tinymce-skin/img/object.gif
Error: SSL read failed in /Users/pad/Sites/devel/ftp-deployment/src/Deployment/CliRunner.php:181

Deployment\ServerException: SSL read failed in /Users/pad/Sites/devel/ftp-deployment/src/Deployment/CliRunner.php:181
Stack trace:
#0 [internal function]: Deployment\CliRunner->Deployment\{closure}(2, 'SSL read failed', '/Users/pad/Site...', 141, Array)
#1 /Users/pad/Sites/devel/ftp-deployment/src/Deployment/FtpServer.php(141): ftp_nlist(Resource id #37778, '/wp-content/plu...')
#2 /Users/pad/Sites/devel/ftp-deployment/src/Deployment/FtpServer.php(154): Deployment\FtpServer->removeFile('/wp-content/plu...')
#3 /Users/pad/Sites/devel/ftp-deployment/src/Deployment/Deployer.php(278): Deployment\FtpServer->renameFile('/wp-content/plu...', '/wp-content/plu...')
#4 /Users/pad/Sites/devel/ftp-deployment/src/Deployment/Deployer.php(152): Deployment\Deployer->renamePaths(Array)
#5 /Users/pad/Sites/devel/ftp-deployment/src/Deployment/CliRunner.php(96): Deployment\Deployer->deploy()
#6 /Users/pad/Sites/devel/ftp-deployment/src/deployment.php(26): Deployment\CliRunner->run()
#7 /Users/pad/Sites/devel/ftp-deployment/deployment(3): require('/Users/pad/Site...')
#8 {main}

**Comment by pad52** [comment]
Could it be possible to trigger the renaming phase only instead than running from the beginning?
I have ~ 1.2Gb files.

**Comment by dg** [comment]
I hope this https://github.com/dg/ftp-deployment/commit/42c110a368d3dddafb7a2adc4225c4de5f8dc04f helps you.
