### ISSUE TITLE
Wrong path when expanding JS files

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#123]
Version: 3.1

### Bug Description
When expanding JS files recursively (function `expandApacheImports),` the wrong root file is given. 

### Steps To Reproduce
Imagine you have the following structure:
<pre>
root
  +---- dir1
    +---- file1.js
    +---- file2.js
  +---- dir2
    +---- file3.js
</pre>

Now the `file3.js` include the `file2.js` and `file2.js` include the `file1.js`. It is impossible for the `file2.js` to refer to the `file1.js` because the directory name is `root/dir2` instead of `root/dir1.`

### Expected Behavior
The `$file` parameter must be given instead of `dirname($file)`.

### Possible Solution
Simply replace the `dirname($file)` by `$file` parameter like follow:

`return $this->expandApacheImports(file_get_contents($file), $file);`

**Comment by janpecha** [comment]
How looks content of `file3.js`?

**Comment by laurentmuller** [comment]
The `file3.js` contains: 

`<!--#include file="../dir1/file2.js" -->` 

And the `file2.js` contains:

`<!--#include file="file1.js" -->`

**Comment by janpecha** [comment]
IMHO you are use it wrong - `file3.js` cannot include `file2.js`:

> The value is a path relative to the directory containing the current document being parsed. It cannot contain `../`, nor can it be an absolute path. Therefore, you cannot include files that are outside of the document root, or above the current document in the directory structure. 
> https://httpd.apache.org/docs/2.4/mod/mod_include.html#element.include

**Comment by laurentmuller** [comment]
Ok. You are rights. 

But the question is that the `#include` clause is only used to compress the java script files.

**Comment by laurentmuller** [comment]
I have updated my directory structure and it work fine.

**Comment by dg** [comment]
It seems that it was already fixed by fbef8cc13491775eaca458bda064077a67341ba3
