### ISSUE TITLE
Parallel uploads with FTP

### ISSUE THREAD

**Issue by CWallenberg** [dg/ftp-deployment#130]
Is it possible to add parallel uploads with FTP?
I'm asking because an initial deployment takes about an hour using this project and using `lftp` it takes about 10-15 minutes for an initial deployment.
This addition would speed up both the initial & subsequent deployments.

**Comment by dg** [comment]
It would be very complicated to develop this, I don't plan it.

**Comment by CWallenberg** [comment]
Ok.
