### ISSUE TITLE
Unable to rename file or directory. in phar:///app/deployment.phar/Deployment/CliRunner.php:2

### ISSUE THREAD

**Issue by chinloyal** [dg/ftp-deployment#131]
When reuploading, I keep getting this error for some files 

> Error: /File.dll: Unable to rename file or directory. in phar:///app/deployment.phar/Deployment/CliRunner.php:2

I'm uploading a publish .NET Core project. The uploading was working before but stopped now. I thought it was a permission error at first but all the files on the server have read/write permission. 

I'm using the 3.1 phar file

**Comment by chinloyal** [comment]
I also notice that the line that renames files has a TODO
`Safe::ftp_rename($this->connection, $old, $new); // TODO: zachovat permissions`

**Comment by dg** [comment]
I have no idea what this could cause. Unfortunately, the PHP error message is too vague…

**Comment by chinloyal** [comment]
The issue seemed to be with the server the files were being hosted on, the server would not allow the tool to rename the files while they were running (dll files to be exact). So this does not seem to be the tool's problem.
