### ISSUE TITLE
FTP command rename doesn't work

### ISSUE THREAD

**Issue by Hologos** [dg/ftp-deployment#134]
Version: 3.3.0

### Bug Description
FTP command rename doesn't work in deployment.ini file.

### Steps To Reproduce
Add job

```
before[] = remote: rename www/.maintenance.html www/index.html
```

**The output**

```text
...
Before-jobs:
remote: rename www/.maintenance.html www/index.html
Error: Unknown SITE command.
Error: Unknown SITE command. in /Users/malekjir/Software/Library/ftp-deployment-3.3.0/src/Deployment/FtpServer.php:272
```

### Expected Behavior
File gets renamed on server.

Renaming files works since uploaded files get renamed after successful upload. According to #67, rename command should work, but maybe I misunderstood.

**Comment by dg** [comment]
I think you should use `mv` https://www.cyberciti.biz/faq/unix-command-rename-file/

**Comment by Hologos** [comment]
Sorry, I only tried mv as `ftp: mv .. ..`.
