### ISSUE TITLE
Deployment works with ini configuration, but not with php configuration

### ISSUE THREAD

**Issue by fridde** [dg/ftp-deployment#144]
Version: 3.4.1

I am currently converting my ```deployment.ini``` file to a setup using ```deployment.php``` instead. This looked like a no-brainer, since the keys and array structure are identical (the source code seems to suggest that).

But there either seems to be some subtle difference or I am overlooking something (not too improbable).

### Bug Description
Running ```./vendor/bin/deployment deployment.php``` results in 
```
Error: php_network_getaddresses: getaddrinfo failed: Name or service not known in /mnt/d/staging/project_name/vendor/dg/ftp-deployment/src/Deployment/FtpServer.php:71
```
but running ```./vendor/bin/deployment deployment.ini``` with the identical settings works flawlessly.

Even if I would look into the error itself and tried to solve this on a deeper level, the behaviour would still be completely unexpected, as the configuration layer should be completely decoupled from the implementation.

I have uploaded my files to [this gist](https://gist.github.com/fridde/cf0e5add501690bf51f68240c03b0bfd) with sensitive details replaced.

I am running this on a Windows 10 machine using WSL2 and PHP 8.0 (if that's relevant).

**Comment by dg** [comment]
And is the ini file parsed correctly? Are there any quotes missing?

**Comment by fridde** [comment]
I think there might be some confusion: Using an ini-file *works*, it's when I use the php file as the source of configuration the error comes up.

Searching for the error seems to indicate that some network setting might not be in order, but that just leads to the question why the exact same values work when I use the ini-file.

I have double-checked that every value is identical (with "Yes"/"No" exchanged for true/false). See the gist I linked to.

So either I am overlooking something (most probable, to be honest) or there is some serious leaking going on between how the files are translated into the configuration array and how the deployment is executed. The deployment should be completely unaware of the config file used.

I just wanted to check if you had an initial idea on where to look. But please don't put any effort into this, I am getting by just fine. This package has been great for me who only can deploy via ftp.

**Comment by fridde** [comment]
The issue was on my side. After a lengthy debugging process I saw that even though I had made sure that the values in both deployment.ini and deployment.php were identical, I was editing the *wrong deployment.php file* all the time.

I have a development area and a staging area. The staging area is basically just a temporary folder that is then synced to the server. While debugging, I was making sure the deployment.ini *in the staging area* and the deployment.php *in the dev area* were identical. The deployment.php in the staging area had a typo in the url.

Please excuse me while I go contemplate my life.
