### ISSUE TITLE
Error: Authentication failed for web using public key

### ISSUE THREAD

**Issue by xpader** [dg/ftp-deployment#150]
Version: 3.4.0

### Bug Description
Error: Authentication failed for web using public key: Callback returned error in phar:///home/pader/deployment.phar/src/Deployment/SshServer.php:2      

Error on debian linux with php 8.0.10.
But normal on my mac with php 8.0.10.

**Comment by dg** [comment]
I can't solve this, I don't use Linux. If you find a fix, post a PR.
