### ISSUE TITLE
More deployment sections but common configuration

### ISSUE THREAD

**Issue by vodictomas** [dg/ftp-deployment#151]
We deploy our app to more instances via CI, but deploy configuration (ignore, before, after...) is the same for all of them.

Would be cool if there is any possibility to achieve this, rather than copying the configuration to each section.

Few ideas:
- marking a section as default and configuration in it would merge with other sections
- new optional parameter, which would load common configuration from specified .ini file
- not creating any section or remote, but set custom remote via optional parameter

Any thoughts on this?

**Comment by kravcik** [comment]
And most important thing - we will prepare Pull Request. Just asking for opinion @dg. :)

**Comment by vodictomas** [comment]
I didn't realize this can be easily done with .php config file, so all good :)
