### ISSUE TITLE
SITE EXEC not understood

### ISSUE THREAD

**Issue by ZdenekKrcal** [dg/ftp-deployment#155]
Version: 3.5.1

after[] = remote: php app/artisan optimize:clear

After-jobs:        
remote: chmod 0776 app/bootstrap/cache        
remote: php app/artisan optimize:clear        
Error: Deployment\ServerException: 'SITE EXEC' not understood in phar

**Comment by dg** [comment]
You'll have to investigate that deeply.

**Comment by ZdenekKrcal** [comment]
it is not possible to call command:   php something.php

**Comment by dg** [comment]
The FTP server simply does not allow it.

**Comment by ZdenekKrcal** [comment]
But you have solved same problem with chmod here:

https://github.com/dg/ftp-deployment/issues/142

**Comment by dg** [comment]
Because it was possible to use the ftp_chmod() function. For others command is used ftp_exec() and the server doesn't seem to support it.
