### ISSUE TITLE
Invalid badge in readme.md file.

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#167]
Version: 3.6.0

### Description
The [readme.md](https://github.com/dg/ftp-deployment#readme) file contain a invalid link for the Tests badge:

![image](https://github.com/dg/ftp-deployment/assets/4330059/0fc26033-11d9-4bf8-8e8f-4dd530384347)

### Possible Solution
Update the link.

**Comment by dg** [comment]
fixed
