### ISSUE TITLE
add possibility to login via SSH key

### ISSUE THREAD

**Issue by rebendajirijr** [dg/ftp-deployment#48]
Please, add possibility to set public/private key file when trying to login via SSH key [ssh2_auth_pubkey_file](http://php.net/manual/en/function.ssh2-auth-pubkey-file.php).

**Comment by JanTvrdik** [comment]
Updated URL: http://blog.joncairns.com/2013/12/understanding-ssh-agent-and-ssh-add/

**Comment by george-oakling** [comment]
Is it possible to use Pageant from Putty? SSH agent with MSYS is absolutely non-comfortable...

**Comment by JanTvrdik** [comment]
> SSH agent with MSYS is absolutely non-comfortable.

Why?
