### ISSUE TITLE
SFTP - Chyba při mazání složky.

### ISSUE THREAD

**Issue by kubinpetr** [dg/ftp-deployment#58]
Při použití SFTP mi to hlásí chybu:
```
Error: dir(): Unable to open ssh2.sftp://Resource id #17/www/example.com/
www/temp/cache/.delete54a67b575d74a on remote host in \dg-ftp-deployment\libs\SshServer.php on 159
```

Divné je to, že tato složka ale vůbec neexistuje.
Přijde mi to, jako když to složku smaže, ale pak jí to chce mazat ještě jednou.
Díky tomu, že to vyhodí chybu to proces nedokončí.
Např. v dané složce zbyly ještě 3 .delete..... všechny mají správná práva a chmod 755.

Vyřešil jsem to tak, že jsem v `SshServer#159` nahradil `dir(` za `@dir(` a následující `while` obalil do `if ($iterator) { ... }`

Udělal jsem několik uploadů, aktualizací a po této úpravě nikdy nebyl problém.

**Comment by dg** [comment]
Možná by to mohlo vyřešit tohle 877b5713f29bc9a25eb3344a7450ed6e9b39bccb

**Comment by kubinpetr** [comment]
Bohužel. NIcméně zajímavé je to, že mazaná složka končí 0, tedy count($dirs) === 0.
Zkusil jsem ještě na konec řádku přidat 3x rand(0,9), ale problém nastane stejně.

Nejhorší je, že se to stane jen někdy. jednou to projde, podruhé ne.

**Comment by dg** [comment]
Můžeš zkusit vyzkoumat, proč se to děje, třeba před každý příkaz echo a zjistit, kde adresář zmizí?

**Comment by kubinpetr** [comment]
Nemám stím problém. Kam přesně, resp. co přesně, mám logovat?

**Comment by dg** [comment]
To nevím, prostě zkusit vypátrat, proč se to stává.

**Comment by kubinpetr** [comment]
Ok. Tak první poznatek.
"Dumpnul" jsme si přejmenování složky. Přejmenuje to složku na ".delete53a9071aabbb9" a přesně na té samé složce to selže při mazání (viz chyby hore). => vypadá to, že se nepovede přejmenování složky. Nicméně php nic nehlásí.

Zkusil jsem tedy nahradit:
```
$this->protect('rename', ["$path/$file", "$path/$tmp"]);
```
za
```
rename("$path/$file", "$path/$tmp");
```

Díky této změně dojde ke smazání a neskončí to žádným errorem.

**Comment by dg** [comment]
To je hodně divné, protože `protect()` nastaví error handler a ten stejný rename volá…

**Comment by dg** [comment]
Btw, pro mazání složek přes ssh používám `after =  'remote: rm -rf /path/.../temp/*'`, je to rychlejší, teda pokud to server podporuje.

**Comment by kubinpetr** [comment]
Jinak mám Windows, Apache: v2.4.10 PHP: v5.5.20, pokud to nějak pomůže.

**Comment by kubinpetr** [comment]
Řekl bych, že konečně poznatek, který by mohl pomoc k řešení.
Projekt je na nette a v purge mám `temp\cache`. Před mazáním obsahuje 3 složky `_Nette.RobotLoader, latte a Nette.Configurator` jak je vidět v tomto logu, tak se to z nějakého záhadného důvodu zacyklí a přejmenovává to již přejmenované.

Tento log je vytvořen před zavoláním s call_user_func_array(...);
http://pastebin.com/QKxviaaV
Samozřejmě v sekci `purge` mám `temp/cache` pouze jednou.

**Comment by dg** [comment]
@kubinpetr můžeš zkusit tohle? https://github.com/dg/ftp-deployment/commit/537ad109405557821bf193d7ed7e092df122d020

**Comment by kubinpetr** [comment]
Vypadá to v pořádku :+1: Díky.

**Comment by dg** [comment]
Super
