### ISSUE TITLE
Yuicompressor - split to composer

### ISSUE THREAD

**Issue by f3l1x** [dg/ftp-deployment#65]
Yuicompressor is available via composer package.

https://packagist.org/packages/nervo/yuicompressor

Ftp-deployment could suggest this package. What do you think?

**Comment by hyyan** [comment]
+1

**Comment by dg** [comment]
Why?

**Comment by hyyan** [comment]
@dg Isn't just better to let composer handle vendors , so we can keep up to data with latest  , And I would suggest to use https://packagist.org/packages/neeckeloo/closure-compiler-php package too if that possible 

@dg what do you think ?

**Comment by dg** [comment]
I don't know whether is it better to rely on Nervo and Neeckeloo. Are they authorities?

**Comment by dg** [comment]
Java Closure Compiler can be replaced by online tool https://developers.google.com/closure/compiler/docs/gettingstarted_api.

**Comment by hyyan** [comment]
@dg it agree clean Css seems better , but using it means that the project will depend on node.js , for the Nervo and Neeckeloo. packages probably you have a point here they are not trusted , I prefer using tools like [UglifyJS](https://github.com/mishoo/UglifyJS) and [Clean Css](https://github.com/jakubpawlowicz/clean-css) which depends on node.js
