### ISSUE TITLE
Support standard FTP commands

### ISSUE THREAD

**Issue by geedmo** [dg/ftp-deployment#67]
Hi, 
Currently, any command sent to the server requires SITE EXEC
For example, 
``` php
before[] = remote: mkdir somefolder
before[] = remote: cd somefolder
```
But, some commands like above could be executed without such extension, so, would nice to have an option to run standard ftp commands like 
``` php
before[] = ftp: mkdir somefolder
before[] = ftp: cd somefolder
```
I'm not sure if this is viable from your side, but my proposal is add new ftp method to the Server interface, and then perform
``` php
...
 elseif ($m[1] === 'ftp') {
  $out = $this->server->ftp($m[2]);
...
```
Or perhaps, use a small list with the few standard ftp commands and switch to the ftp method.

Thanks

**Comment by foxycode** [comment]
@dg I'd like this too. It worked in earlier version, now I can't do simple things like chmod after deploy.

**Comment by dg** [comment]
Do you remember in which version it worked?

**Comment by foxycode** [comment]
Definitely before 2.0, not sure about specific version, but 1.3 was probably ok,

**Comment by dg** [comment]
I see only `file_get_contents` before 2.0. Are you sure?

**Comment by foxycode** [comment]
I searched my old repositories an find out I used version 1.3, but didn't find old deploy config. I used something like this in new config:
```
after[] = remote: mv app/config/config.test.neon app/config/config.local.neon
after[] = remote: chmod 777 log
after[] = remote: chmod 777 temp
```
and it doesn't work without site commands support. I think it worked earlier somehow, maybe by some workaround before `remote:` support, but I am not sure, it is long time ago.

Point is, it will be awsome if basic ftp commands like mv and chmod could work without site commands support.

**Comment by dg** [comment]
FTP has these functions:

~~`ftp_cdup` — Changes to the parent directory~~ duplicated `chdir ..`
~~`ftp_chdir` — Changes the current directory on a FTP server~~ IMHO safer is to use absolute paths, this can complicate whole process
`ftp_mkdir` — Creates a directory - can be emulated
`ftp_rmdir` — Removes a directory - can be emulated
~~`ftp_chmod` — Set permissions on a file via FTP~~ requires SITE internally
~~`ftp_get` — Downloads a file from the FTP server~~ IMHO makes no sense to download file
~~`ftp_put` — Uploads a file to the FTP server~~ IMHO uploading files should be done by Deployment core
`ftp_delete` — Deletes a file on the FTP server - can be emulated
`ftp_rename` — Renames a file or a directory on the FTP server - can be emulated

So `mkdir`, `rmdir`, `delete` and `rename` can be emulated.

**Comment by foxycode** [comment]
I did some testing. The actual problem is `site exec` command, not `site` alone, which is supported by FTP servers where I had problems earlier.
```
Error: SITE EXEC is an unknown extension
```
When I do chmod using Total Commander, it uses `SITE CHMOD` command which is supported. So maybe `ftp_site` function can be solution.

**Comment by foxycode** [comment]
I can't find which commands are supported across most common FTP servers, so I tried to list them from on of problematic FTP servers. Looks like only two of them are really standard.
```
SITE HELP
214-The following SITE commands are recognized (* =>'s unimplemented)
214-HELP
214-CHGRP
214-CHMOD
``

**Comment by dg** [comment]
chgrp is probably not needed to emulate…

**Comment by foxycode** [comment]
Tested and working :+1: 

Many thanks as always :-)
