### ISSUE TITLE
SshServer replacement using phpseclib/phpseclib

### ISSUE THREAD

**Issue by george-oakling** [dg/ftp-deployment#68]
I am implementing replacement of SshServer, by using pure PHP SSH2/SFTP library phpseclib, because PHP 5.6 PECL has no php_ssh2.dll. The thing is that I cant find a perfect solution for including the phpseclib (composer require phpseclib/phpseclib) in Deployment. Should I make it optional composer requirement? And how to include it in SshServer.php? Deployment does not use composer autoloader, so now I have hardcoded hack in the file: include __DIR__ . '/../../../../autoload.php'; which is ugly and non-systematic.

**Comment by dg** [comment]
Are you looking for php_ssh2.dll for PHP 5.6 or 7.0? 
- https://files.nette.org/misc/5.6-x86/php_ssh2.dll 
- https://files.nette.org/misc/5.6-x64/php_ssh2.dll
- https://files.nette.org/misc/7.0-x86/php_ssh2.dll 
- https://files.nette.org/misc/7.0-x64/php_ssh2.dll

**Comment by ne0-cz** [comment]
Could you provide an example how to install your DLLs via composer? How does this affect non-Windows environments?

Much easier would be just add PHP < 7 requirement into `composer.json`, nobody would expect deployment to work with PHP 7 then...

**Comment by dg** [comment]
How it install DLL is describet here http://php.net/manual/en/install.pecl.php (DLL is only for Windows).

FTP Deployment works with PHP 7.

**Comment by ne0-cz** [comment]
> FTP Deployment works with PHP 7.

Interesting. FTP Deployment is the reason I had to downgrade from PHP 7 to PHP 5.6.

Providing your own DLLs doesn't make it any better. Even if I used Windows, I don't feel like using some random DLL downloaded from the internet (OTOH I know most Windows users don't mind at all).

Why do you prefer PHP module with last release from 2012-10-15 over the phpseclib?

**Comment by dg** [comment]
Where is problem?
