### ISSUE TITLE
Stuck at compressing JS file

### ISSUE THREAD

**Issue by hantc** [dg/ftp-deployment#70]
I was testing ftp deployment yesterday on two computers, strange thing happened, one of computers out of nowhere started to stuck at compressing one jquery plugin. (nothing was changed between deploys)

When I try to compress that jquery plugin in cmd, everything works well.

Does someone experienced a similar issue? Testing it a couple of hours now, but no bigger progress so far.

Thanks

**Comment by dg** [comment]
Java-based compression was replaced with online tool, I hope it will not stuct anymore.
