### ISSUE TITLE
ask for credentials

### ISSUE THREAD

**Issue by TheJetlag** [dg/ftp-deployment#75]
I really don't like storing my ftp credentials in the code. Is there any way for providing credentials on request?

**Comment by mbohal** [comment]
We encrypt the deployment scripts with gpg. See https://github.com/mbohal/gpg-ftp-deployment. It works with linux and mac. 
I'm unsure if it is compatible with the latest version of ftp-deployment. If not, patch is welcome though....

**Comment by janedbal** [comment]
Instead of ini config file, you can use php with credentials prompt.

```php
$username = 'www-user';
echo "Enter password for $username: ";
exec('stty -echo 2>&1');
$password = stream_get_line(STDIN, 1024, PHP_EOL);
exec('stty echo 2>&1');

return [
    'ProjectName' => [
        'remote' => 'sftp://'.$username.':' . trim($password) . '@host:port',
        // ...
    ],
];

```

**Comment by dg** [comment]
@janedbal :+1:

**Comment by tmsbrg** [comment]
If you're not very comfortable writing PHP(like me) you can make a Bash script like this:

```bash
#!/bin/bash
TMP=_deployment.ini.tmp
read -sp "Password: " PASSWORD
echo
sed "s/PASSWORD/$PASSWORD/" _deployment.ini > $TMP &&
    jekyll build &&
    deployment $TMP
shred -un 1 $TMP
```

It takes the _deployment.ini file(I put an underscore in front of it for Jekyll), and replaces wherever you type PASSWORD with the password you enter.
