### ISSUE TITLE
ftp address and login details split to separate lines

### ISSUE THREAD

**Issue by corvannoorloos** [dg/ftp-deployment#83]
Hello,

Would it also be possible to have my login details and ftp address split to separate lines instead of a single remote address?

```ini
[my site] ; There may be more than one section
; remote FTP server
; remote = ftp://user:secretpassword@ftp.example.com/directory
user = "user"
pass = "secretpassword"
host = "ftp.example.com/directory"
```

**Comment by dg** [comment]
`host` is not correct, because `ftp.example.com/directory` is combination of host & path. What about this?

```
[my site] ; There may be more than one section
remote = ftp://ftp.example.com/directory
user = "user"
pass = "secretpassword"
```

Can you send pull request?

**Comment by corvannoorloos** [comment]
This would be a great addition to have. But I'm unfortunately not knowledgeable enough to handle this request.

**Comment by corvannoorloos** [comment]
Thanks! :smiley:
