### ISSUE TITLE
after: not run when "Already synchronized."

### ISSUE THREAD

**Issue by ne0-cz** [dg/ftp-deployment#88]
The `after` jobs are not run when there's nothing to synchronize - I completely understand this behavoir, but could there be some `afterAlways` implemented?

My use case:

```
'before' => [
    'local: composer install --no-dev'
],
'after' => [
    'local: composer install'
],
```

I don't like uploading dev requierements to production server. And yes, doing deployment when there's nothing to do is kind of edge-case. Does this make sense at all? TY

**Comment by dg** [comment]
Create batch file like:

/--
composer install --no-dev
php deployment
composer install
\--

**Comment by ne0-cz** [comment]
@dg yea, maybe the `composer install` at the end of a batch file could work.

But the `composer install --no-dev` can't be called before the deployment script: this command will actually uninstall the ftp-deployment, so it won't work at all :)

The call to `--no-dev` must be called via deployment script itself.

So in the end this solution can work but is more error prone I think. There'll be one operation in the deployment config and the opposite operation will be in a different place - the batch file which calls the deployment script.

Or maybe I just want too complex deployment scenarios for this script, who knows...

**Comment by dg** [comment]
Do you think that it is better when composer uninstalls deployment script when is used? It can lead to strange errors. IMHO best way is to install Deployer globally.
