### ISSUE TITLE
Error when upload large amount of files

### ISSUE THREAD

**Issue by narendragd** [dg/ftp-deployment#91]
@dg 
exception 'Deployment\FtpException' with message '1 matches total' in /opt/lampp/htdocs/ftpwrapper/src/Deployment/FtpServer.php:303

Stack trace:

#0 [internal function]: Deployment\FtpServer->Deployment\{closure}(2, 'ftp_rename(): 1...', '/opt/lampp/htdo...', 306, Array)

#1 [internal function]: ftp_rename(Resource id #5766, '/lib/Mage/Backu...', '/lib/Mage/Backu...')

#2 /opt/lampp/htdocs/ftpwrapper/src/Deployment/FtpServer.php(306): call_user_func_array('ftp_rename', Array)

#3 /opt/lampp/htdocs/ftpwrapper/src/Deployment/FtpServer.php(290): Deployment\FtpServer->protect('ftp_rename', Array)

#4 /opt/lampp/htdocs/ftpwrapper/src/Deployment/FtpServer.php(145): Deployment\FtpServer->ftp('rename', '/lib/Mage/Backu...', '/lib/Mage/Backu...')

#5 /opt/lampp/htdocs/ftpwrapper/src/Deployment/Deployer.php(286): Deployment\FtpServer->renameFile('/lib/Mage/Backu...', '/lib/Mage/Backu...')

#6 /opt/lampp/htdocs/ftpwrapper/src/Deployment/Deployer.php(153): Deployment\Deployer->renamePaths(Array)

#7 /opt/lampp/htdocs/ftpwrapper/src/Deployment/CliRunner.php(94): Deployment\Deployer->deploy()

#8 /opt/lampp/htdocs/ftpwrapper/src/deployment.php(23): Deployment\CliRunner->run()

#9 /opt/lampp/htdocs/ftpwrapper/deployment(3): require('/opt/lampp/htdo...')

#10 {main}

NOTE: We are facing this above exception issue while renaming files after upload via system so could you please help us to sort out this issue.

You can reply at below given email address.

Email: narendra.dangi@sufalamtech.com

Regards
Narendra Kumar Dangi

**Comment by dg** [comment]
I don't know what to do about it.
