### ISSUE TITLE
Change directory after connecting to server

### ISSUE THREAD

**Issue by arron0** [dg/ftp-deployment#92]
Hi,

i have directory on server, which can't be deleted, but I see no way how to switch deployment to deploy to this directory.
When configured like this:
remote = sftp://host.cz/www
it is trying to create that www directory instead of switching into it. Is there any way how to overcome this?

Thank you.

**Comment by arron0** [comment]
It looks like the file_exists("ssh2.sftp://$this->sftp$dir") in https://github.com/dg/ftp-deployment/blob/master/src/Deployment/SshServer.php#L136 keeps returning false even when directory exists. It's very hard to make typo in 'www' name of the directory and even when i run $this->execute('ls') when debuging (or $this->execute('cd www')) it is returning 'www' direcotry (or it is switching me to that directory). So it looks like real problem with file_exists function :-/

**Comment by ne0-cz** [comment]
@arron0 See https://github.com/dg/ftp-deployment/issues/87#issuecomment-274865571 - aren't you affected by the bug in mod-ssh2 as well? It surely seems so to me.

**Comment by dg** [comment]
Human timeout
