### ISSUE TITLE
Chyba při nahrávání na konkrétní server

### ISSUE THREAD

**Issue by DenisMatyjasko** [dg/ftp-deployment#96]
Zdravím,
mám jeden problém s tímto jinak super nástrojem. 

Při deploymentu projektu na webhosting (forpsi) mi to vždy skončí chybou. Problém je ale komplikovanější. Jde o to že, když provádím deployment např. doma tak vše funguje bez problému, jakmile se pokusím deployment provést na jiném (konkrétním) wifi připojení tak mi to vždy skončí chybou, ale pokud na stejném wifi připojení u kterého nefunguje deployment na forpsi se pokusím nahrát projekt na jiný webhosting (wedos) tak tam to běží bez problému.

Přikládám výpis z logu:

```
Creating remote file .deployment.running
Error: 0.108 seconds (measured here), 1.46 Mbytes per second

Deployment\FtpException: 0.108 seconds (measured here), 1.46 Mbytes per second in C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\FtpServer.php:303
Stack trace:
#0 [internal function]: Deployment\FtpServer->Deployment\{closure}(2, '0.108 seconds (...', 'C:\\ampps\\bold-i...', 306, Array)
#1 [internal function]: ftp_chdir(Resource id #20, '/www')
#2 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\FtpServer.php(306): call_user_func_array('ftp_chdir', Array)
#3 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\FtpServer.php(290): Deployment\FtpServer->protect('ftp_chdir', Array)
#4 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\FtpServer.php(192): Deployment\FtpServer->ftp('chdir', '/www')
#5 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\FtpServer.php(155): Deployment\FtpServer->isDir('/www')
#6 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\Deployer.php(137): Deployment\FtpServer->createDir('/www')
#7 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\Deployment\CliRunner.php(94): Deployment\Deployer->deploy()
#8 C:\ampps\xxx\xxx\vendor\dg\ftp-deployment\src\deployment.php(23): Deployment\CliRunner->run()
#9 C:\ampps\xxx\xxx\deployment(3): require('C:\\ampps\\bold-i...')
#10 {main}
```

verze ftp-deploymentu: 2.7

Rád bych se zeptal zda-li pro tento problém existuje nějak vysvětlení.
Děkuji.

**Comment by robovarga** [comment]
nemoze byt problem ze na hostingu mas povoleny pristup len z niektorych IP. resp krajin?

**Comment by dg** [comment]
Může, těžko říct. Odkud se berou ty zprávy `0.108 seconds (measured here), 1.46 Mbytes per second` vůbec netuším.
