### ISSUE TITLE
[Feature request] Allow deployment of only one site/section

### ISSUE THREAD

**Issue by cedx** [dg/ftp-deployment#97]
- bug report? no
- feature request? yes
- version: 2.8

### Description
I've setup several targets/sites in my `deployment.ini` file. Each section matches a target environment : e.g. `dev`, `prod`, `staging`...

It would be cool if I could run something like:

```shell
deployment --target=prod deployment.ini
```

Currently, all targets/sites are deployed (and deploying to several servers at once is quite unusual). I still can use one `deployment.ini` file per target... but I find more manageable to have all settings in only one file.

### Steps To Reproduce
Input file:

```ini
log = var/deployment.log

[dev]
remote = [...]
local = build
preprocess = no

[prod]
remote = [...]
local = build
preprocess = no

[staging]
remote = [...]
local = build
preprocess = no
```

**Comment by dg** [comment]
It sounds good. Can you try to send pull request?

**Comment by cedx** [comment]
I can try... :sweat_smile:
Do you have any preference for the name of the new CLI argument?

- `section`
- `site`
- `target`
- another proposal?

**Comment by dg** [comment]
Thanks!
